kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  ssl-redirect: "true"
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
